In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.4


In [4]:
## 1. creating arrays

In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [8]:
print(arr_list1.ndim)

1


In [9]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr_list1_2.ndim)

2


In [11]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(arr_list1_3.ndim)

3


In [13]:
#2. numpy array attributes

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print("Shape",arr1.shape)
print("Size",arr1.size)
print("dType",arr1.dtype)
print("n_dim",arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [16]:
# HW: create 2 array- 1D and 3D, and find its attributes

In [17]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [18]:
print("Size",arr1.size)
print("Shape",arr1.shape)
print("dtype",arr1.dtype)
print("n_dim",arr1.ndim)
print("Total Bytes",arr1.nbytes)

Size 6
Shape (6,)
dtype int64
n_dim 1
Total Bytes 48


In [19]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
print(type(arr3))

<class 'numpy.ndarray'>


In [21]:
print("Size",arr3.size)
print("Shape",arr3.shape)
print("dtype",arr3.dtype)
print("n_dim",arr3.ndim)
print("Total Bytes",arr3.nbytes)

Size 8
Shape (2, 2, 2)
dtype int64
n_dim 3
Total Bytes 64


In [22]:
#3. Array initialization method

In [23]:
# zeros array

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# one array

one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [25]:
# full array

full_arr = np.full((3,2),9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [26]:
# Identity Matrix

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# empty array

print(np.empty(2))

[ 6.95334639e-310 -2.00000191e+000]


In [28]:
# evenly spacce array
print(np.arange(2,10,2))

[2 4 6 8]


In [29]:
# specific number of equally (spaced) values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [30]:
# random values array --float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.92647434 0.25676633]
 [0.19930292 0.11917163]
 [0.76900221 0.16016361]]


In [31]:
# arndom values array --int
rint_arr = np.random.randint(1,100,(3,2))
print(rint_arr)

[[35 94]
 [ 2 45]
 [31 39]]


In [32]:
#4. Array indexing and slicing

In [33]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [34]:
print(a[4])

9


In [35]:
print(a[0])

1


In [36]:
print(a[-4])

3


In [37]:
print(a[-1])

9


In [38]:
# Slicing : 
# array[start:stop:step]
#stop-index,that is not included in output
a = np.array([1,3,5,7,9])
print(a)


[1 3 5 7 9]


In [39]:
print(a[0:3]) # First 3 elements

[1 3 5]


In [40]:
print(a[-3:]) #last 3 elements

[5 7 9]


In [41]:
print(a[1:4]) # middle 3 elements

[3 5 7]


In [42]:
print(a[0:4:2]) # steps

[1 5]


In [43]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [44]:
print(arr2[1][0])

4


In [45]:
print(arr2[1])
print(arr2[1:])

[4 5 6]
[[4 5 6]]


In [46]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [47]:
print(arr2[:,0])

# 2D: [rows,columns]
# 3D: [layers/height,rows,columns]

[1 4]


In [48]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [50]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [51]:
print(arr3[:,0])  # 1st column value
print(arr3[:,2]) # last column value

[1 4 7]
[3 6 9]


In [52]:
print(arr3[::2, 0])

[1 7]


In [53]:
print(arr3[1::,1]) #slicing on rows and columns

[5 8]


In [54]:
print(arr3[::,1]) # slicing on columns

[2 5 8]


In [55]:
#5. Array Reshaping and flattening

In [56]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [57]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [58]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [59]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [60]:
#6.Array Stacking and Splitting

In [61]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [62]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [63]:
split =np.hsplit(c,3)

for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [64]:
vsplit =np.vsplit(c,2)

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [65]:
#7.Mathematical Operations on Array

In [66]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [67]:
print(a+10)
print(a-30)
print(a*2)
print(a/10)

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [68]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [69]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [70]:
#8.Mathematical Operations on Multiple Arrays

In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [72]:
print(np.add(a,b))

[5 7 9]


In [73]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [74]:
print(np.dot(a,b)) #dot product

32


In [75]:
print(a.T) #Transpose

[1 2 3]


In [76]:
t = np.array([[1,2,3],[4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [77]:
#9.Statistical functions

In [78]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [79]:
print(np.sum(a))

21


In [80]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [81]:
#10.Array Cpmparison

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [83]:
print(a==b)#comapring each elements
print(np.array_equal(a,b))#comapring complete array

[False False False]
False


In [84]:
#11.Broadcasting

In [85]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)

[6 7 8 9]


In [86]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [87]:
#12.Handling with Null values & infinite

In [88]:
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [89]:
print(np.isnan(data1))

[False False  True False False]


In [90]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [91]:
#save and load arrays

In [92]:
arr = np.array([1,0,0,8])
print(arr)
np.save("my_array.npy",arr)

[1 0 0 8]


In [93]:
loaded_arr = np.load("my_array.npy")
print(loaded_arr)

[1 0 0 8]


In [94]:
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [95]:
print(matrix[-1])

[21 22 23 24 25]


In [97]:
print(matrix[:,0])

[ 1  6 11 16 21]


In [98]:
print(matrix[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
